name: Deploy to Swarm

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-deploy]
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Get latest image tags
      id: get_tags
      run: |
        TAG1=$(docker run --rm ghcr.io/${{ github.repository_owner }}/test-back:latest cat /app/VERSION)
        echo "::set-output name=test-back_tag::${TAG1}"
        TAG2=$(docker run --rm ghcr.io/${{ github.repository_owner }}/test-front:latest cat /app/VERSION)
        echo "::set-output name=test-front_tag::${TAG2}"
        TAG3=$(docker run --rm ghcr.io/${{ github.repository_owner }}/test-network:latest cat /etc/nginx/VERSION)
        echo "::set-output name=test-network_tag::${TAG3}"

    - name: Remove old image versions
      run: |
        echo "Removing old image versions..."
        docker image rm $(docker image ls ghcr.io/${{ github.repository_owner }}/test-back --format '{{.ID}}' | tail -n +4) || true
        docker image rm $(docker image ls ghcr.io/${{ github.repository_owner }}/test-front --format '{{.ID}}' | tail -n +4) || true
        docker image rm $(docker image ls ghcr.io/${{ github.repository_owner }}/test-network --format '{{.ID}}' | tail -n +4) || true

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ghcr.io/${{ github.repository_owner }}/test-back:${{ steps.get_tags.outputs.test-back_tag }}
          docker pull ghcr.io/${{ github.repository_owner }}/test-front:${{ steps.get_tags.outputs.test-front_tag }}
          docker pull ghcr.io/${{ github.repository_owner }}/test-network:${{ steps.get_tags.outputs.test-network_tag }}
          
          docker service update --image ghcr.io/${{ github.repository_owner }}/test-back:${{ steps.get_tags.outputs.test-back_tag }} test-back || docker service create --name test-back --network app-network --replicas 1 ghcr.io/${{ github.repository_owner }}/test-back:${{ steps.get_tags.outputs.test-back_tag }}
          docker service update --image ghcr.io/${{ github.repository_owner }}/test-front:${{ steps.get_tags.outputs.test-front_tag }} test-front || docker service create --name test-front --network app-network --replicas 1 ghcr.io/${{ github.repository_owner }}/test-front:${{ steps.get_tags.outputs.test-front_tag }}
          docker service update --image ghcr.io/${{ github.repository_owner }}/test-network:${{ steps.get_tags.outputs.test-network_tag }} test-network || docker service create --name test-network --network app-network --publish 80:80 --replicas 1 ghcr.io/${{ github.repository_owner }}/test-network:${{ steps.get_tags.outputs.test-network_tag }}
